language: node_js
node_js: ["4.4.7"]
install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
before_script:
  - bower install
script:
  - gulp test-src
  - gulp test-dist-concatenated
  - gulp test-dist-minified
